### ISSUE TITLE
PanicException: NormalizedString bad split

### ISSUE THREAD

**Issue by aimanakheel** [huggingface/tokenizers#1014]
Hi Folks,

Im running the following script
tokenizers.__version__ is 0.12.1
```

import os
from tokenizers import ByteLevelBPETokenizer 
os.environ["RUST_BACKTRACE"] = "full"

tokenizer = ByteLevelBPETokenizer(unicode_normalizer='nfc',
                                 lowercase=True)

tokenizer.train(files=<Training file that contains 60 million sentences >, 
                vocab_size=52000, 
                min_frequency=1, 
                special_tokens=[
                    "<s>",
                    "<pad>",
                    "</s>",
                    "<unk>",
                    "<mask>",
                ],
                show_progress=True
               )
```
Getting the following exception

```
thread '<unnamed>' panicked at 'NormalizedString bad split', /__w/tokenizers/tokenizers/tokenizers/src/tokenizer/normalizer.rs:698:30
stack backtrace:
   0:     0x7fb243901f7d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fb243901f7d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb243901f7d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fb243901f7d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fb24392684c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fb2438fc068 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7fb243904457 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fb243904457 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fb243904457 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7fb243904120 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7fb243904ba9 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x7fb243904897 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:     0x7fb243902444 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7fb2439045a9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x7fb2433d3b83 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x7fb243924981 - core::panicking::panic_display::hb184394d54dc8360
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:73:5
  16:     0x7fb24392492b - core::panicking::panic_str::ha42887cd972750c9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:56:5
  17:     0x7fb2433d39f6 - core::option::expect_failed::h9159c9d16ed9fb7c
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:1852:5
  18:     0x7fb243650b32 - alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter::h982a89b61145da63
  19:     0x7fb243622abb - tokenizers::tokenizer::normalizer::NormalizedString::split::h8a23c233dba48915
  20:     0x7fb2435da522 - tokenizers::tokenizer::pre_tokenizer::PreTokenizedString::split::h8d2aa2cedc05f2eb
  21:     0x7fb2435f838f - <tokenizers::pre_tokenizers::PreTokenizerWrapper as tokenizers::tokenizer::PreTokenizer>::pre_tokenize::h9bf28eaecbf68bd8
  22:     0x7fb2434b9a49 - <tokenizers::pre_tokenizers::PyPreTokenizerTypeWrapper as tokenizers::tokenizer::PreTokenizer>::pre_tokenize::h51f5b969dfc12ec0
  23:     0x7fb24347bde1 - tokenizers::tokenizer::TokenizerImpl<M,N,PT,PP,D>::do_pre_tokenize::hf2b4d7142ba1770b
  24:     0x7fb2434f953c - tokenizers::tokenizer::TokenizerImpl<M,N,PT,PP,D>::train_from_files::{{closure}}::{{closure}}::h77c50e9382506d07
  25:     0x7fb2434f5299 - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume::hce49aad0a60d82da
  26:     0x7fb2435354f8 - <rayon::iter::par_bridge::IterParallelProducer<Iter> as rayon::iter::plumbing::UnindexedProducer>::fold_with::hfad09183f8867289
  27:     0x7fb2434e9a06 - rayon::iter::plumbing::bridge_unindexed_producer_consumer::h7e300bb820a304fa
  28:     0x7fb24359bfc3 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h488932459259a537
  29:     0x7fb2433c6b9f - rayon_core::registry::WorkerThread::wait_until_cold::h1c0f45f8c8086769
  30:     0x7fb24368ceb9 - rayon_core::registry::ThreadBuilder::run::h99db3c79c2d6f14a
  31:     0x7fb24368f421 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc64be42a9cc1e97d
  32:     0x7fb24368b0dd - core::ops::function::FnOnce::call_once{{vtable.shim}}::h21dbfc5ab836b6ca
  33:     0x7fb243909e23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf70ac038171e3e1a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  34:     0x7fb243909e23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6690128792365ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  35:     0x7fb243909e23 - std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  36:     0x7fb29c80c44b - start_thread
  37:     0x7fb29bbf840f - __GI___clone
  38:                0x0 - <unknown>
thread '<unnamed>' panicked at 'NormalizedString bad split', /__w/tokenizers/tokenizers/tokenizers/src/tokenizer/normalizer.rs:698:30
stack backtrace:
   0:     0x7fb243901f7d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fb243901f7d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb243901f7d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fb243901f7d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fb24392684c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fb2438fc068 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7fb243904457 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fb243904457 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fb243904457 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7fb243904120 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7fb243904ba9 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x7fb243904897 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:     0x7fb243902444 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7fb2439045a9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x7fb2433d3b83 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x7fb243924981 - core::panicking::panic_display::hb184394d54dc8360
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:73:5
  16:     0x7fb24392492b - core::panicking::panic_str::ha42887cd972750c9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:56:5
  17:     0x7fb2433d39f6 - core::option::expect_failed::h9159c9d16ed9fb7c
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:1852:5
  18:     0x7fb243650b32 - alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter::h982a89b61145da63
  19:     0x7fb243622abb - tokenizers::tokenizer::normalizer::NormalizedString::split::h8a23c233dba48915
  20:     0x7fb2435da522 - tokenizers::tokenizer::pre_tokenizer::PreTokenizedString::split::h8d2aa2cedc05f2eb
  21:     0x7fb2435f838f - <tokenizers::pre_tokenizers::PreTokenizerWrapper as tokenizers::tokenizer::PreTokenizer>::pre_tokenize::h9bf28eaecbf68bd8
  22:     0x7fb2434b9a49 - <tokenizers::pre_tokenizers::PyPreTokenizerTypeWrapper as tokenizers::tokenizer::PreTokenizer>::pre_tokenize::h51f5b969dfc12ec0
  23:     0x7fb24347bde1 - tokenizers::tokenizer::TokenizerImpl<M,N,PT,PP,D>::do_pre_tokenize::hf2b4d7142ba1770b
  24:     0x7fb2434f953c - tokenizers::tokenizer::TokenizerImpl<M,N,PT,PP,D>::train_from_files::{{closure}}::{{closure}}::h77c50e9382506d07
  25:     0x7fb2434f5299 - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume::hce49aad0a60d82da
  26:     0x7fb2435354f8 - <rayon::iter::par_bridge::IterParallelProducer<Iter> as rayon::iter::plumbing::UnindexedProducer>::fold_with::hfad09183f8867289
  27:     0x7fb2434e9a06 - rayon::iter::plumbing::bridge_unindexed_producer_consumer::h7e300bb820a304fa
  28:     0x7fb24359bfc3 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h488932459259a537
  29:     0x7fb2433c6b9f - rayon_core::registry::WorkerThread::wait_until_cold::h1c0f45f8c8086769
  30:     0x7fb24368ceb9 - rayon_core::registry::ThreadBuilder::run::h99db3c79c2d6f14a
  31:     0x7fb24368f421 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc64be42a9cc1e97d
  32:     0x7fb24368b0dd - core::ops::function::FnOnce::call_once{{vtable.shim}}::h21dbfc5ab836b6ca
  33:     0x7fb243909e23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf70ac038171e3e1a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  34:     0x7fb243909e23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6690128792365ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  35:     0x7fb243909e23 - std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  36:     0x7fb29c80c44b - start_thread
  37:     0x7fb29bbf840f - __GI___clone
  38:                0x0 - <unknown>
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/tmp/ipykernel_56211/861800879.py in <cell line: 7>()
      5 tokenizer = ByteLevelBPETokenizer(unicode_normalizer='nfc')
      6 
----> 7 tokenizer.train(files=[config['roberta_mlm_training']['training_file_path']], 
      8                 vocab_size=config['roberta_mlm_training']['tokenizer_vocab_size'],
      9                 min_frequency=config['roberta_mlm_training']['tokenizer_min_frequency'],

~/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/tokenizers/implementations/byte_level_bpe.py in train(self, files, vocab_size, min_frequency, show_progress, special_tokens)
    102         if isinstance(files, str):
    103             files = [files]
--> 104         self._tokenizer.train(files, trainer=trainer)
    105 
    106     def train_from_iterator(

PanicException: NormalizedString bad split

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/tmp/ipykernel_56211/861800879.py in <cell line: 7>()
      5 tokenizer = ByteLevelBPETokenizer(unicode_normalizer='nfc')
      6 
----> 7 tokenizer.train(files=[config['roberta_mlm_training']['training_file_path']], 
      8                 vocab_size=config['roberta_mlm_training']['tokenizer_vocab_size'],
      9                 min_frequency=config['roberta_mlm_training']['tokenizer_min_frequency'],

~/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/tokenizers/implementations/byte_level_bpe.py in train(self, files, vocab_size, min_frequency, show_progress, special_tokens)
    102         if isinstance(files, str):
    103             files = [files]
--> 104         self._tokenizer.train(files, trainer=trainer)
    105 
    106     def train_from_iterator(

PanicException: NormalizedString bad split
```

Any idea what may be causing this issue?

**Comment by aimanakheel** [comment]
Answering my own question, silly mistake was used '/n' instead of '\n' in training data.
