### ISSUE TITLE
[FEATURE] Feature parity between vanilla and fast tokenizers

### ISSUE THREAD

**Issue by jmwoloso** [huggingface/tokenizers#1058]
Hello!

Cc: @SaulLu (you were referenced in the issue below, so I'm assuming you have the context from the OP in that other issue)

Related to: [#1045](https://github.com/huggingface/tokenizers/issues/1045)

The specific scenario described below is one example (there may be more that I haven't encountered) where feature parity is absent between the Rust-based tokenizers from this repo and Python-based tokenizers within `transformers`.

```python
from transformers import DistilBertTokenizer, AutoTokenizer

model = "distilbert-base-uncased"

input = "Hello, tokenizers!"

tokenizer = DistilBertTokenizer.from_pretrained(model)
print(type(tokenizer))

fast_tokenizer = AutoTokenizer.from_pretrained(model)
print(type(fast_tokenizer))

tokens = tokenizer.encode(input)
fast_tokens = fast_tokenizer.encode(input)

# works
tokens = tokenizer.encode(tokens)

# doesn't work; ditto for `encode_plus`
fast_tokens = fast_tokenizer.encode(fast_tokens)
```

The traceback from the second call to `fast_tokenizer` produces a `TypeError`

```bash
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/jason/.virtualenvs/pml/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2278, in encode
    encoded_inputs = self.encode_plus(
  File "/home/jason/.virtualenvs/pml/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2610, in encode_plus
    return self._encode_plus(
  File "/home/jason/.virtualenvs/pml/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 499, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "/home/jason/.virtualenvs/pml/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 426, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
```

As mentioned in the related issue, the docs indicate this should work, yet it doesn't. We could change the `transformers` docs...or we could bring parity to the Rust-based tokenizers (my vote!). 

I'm not experienced with Rust, but I'm starting to learn it, so I'd be happy to tackle at least these subsets (adding functionality to `.encode` and `.encode_plus` methods) of my feature request assuming there is not something inherent in Rust that prevents this from happening.

Also, it may be the case that everywhere else there is parity and these are the only places without it, in which case, this would be the feature instead of a larger feature with an itemized list of differences between the two implementations.

Thanks in advance for the consideration!

**Comment by jmwoloso** [comment]
There are some feasible work-arounds mentioned by @Narsil in [1045](https://github.com/huggingface/tokenizers/issues/1045) and given the cannon described there, it makes sense so I'll close this.
