### ISSUE TITLE
[MASK] token is missing in BERT wordpiece example

### ISSUE THREAD

**Issue by stefan-it** [huggingface/tokenizers#106]
Hi,

in the current example script for BERT with wordpiece:

https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/train_bert_wordpiece.py

the `[MASK]` token is missing. This will lead to the following error message:

```bash
Traceback (most recent call last):                                                      
  File "create_pretraining_data.py", line 469, in <module>                                                                                                                     
    tf.app.run()                                                                                                                                                                         
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run                                                                                  
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)                          
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run                                                      
    _run_main(main, args)                                                                         
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main                                                                            
    sys.exit(main(argv))                                       
  File "create_pretraining_data.py", line 462, in main                                                                                                                                   
    FLAGS.max_predictions_per_seq, output_files)                                                  
  File "create_pretraining_data.py", line 107, in write_instance_to_example_files
    input_ids = tokenizer.convert_tokens_to_ids(instance.tokens)                                                                             
  File "/mnt/histobert3/bert/tokenization.py", line 179, in convert_tokens_to_ids
    return convert_by_vocab(self.vocab, tokens)                                                                                                                                          
  File "/mnt/histobert3/bert/tokenization.py", line 140, in convert_by_vocab
    output.append(vocab[item])                                               
KeyError: '[MASK]'
```

When trying to create the pre-training data for BERT. I checked the original BERT vocab files and it seems that these are the only "special" tokens:

```bash
[PAD]
[UNK]
[CLS]
[SEP]
[MASK]
```

So I think the train command should be:

```
trainer = tokenizer.train(
    files,
    vocab_size=10000,
    min_frequency=2,
    show_progress=True,
    special_tokens=['[PAD]', '[UNK]', '[CLS]', '[SEP]', '[MASK]' ],
    limit_alphabet=1000,
    wordpieces_prefix="##"
)
```

**Comment by n1t0** [comment]
Thank you @stefan-it! I've updated the default special tokens in the `BertWordPieceTokenizer` class as well to reflect that.
