### ISSUE TITLE
Module not found: Error: Can't resolve '../bin-package' in path

### ISSUE THREAD

**Issue by zbloss** [huggingface/tokenizers#1094]
I am getting this error in my react app when I try to load a BertWordPieceTokenizer

```node

const wordPieceTokenizer = await BertWordPieceTokenizer.fromOptions({ vocabFile: "./vocab.txt" });

```

Error:

```
ERROR in ./node_modules/tokenizers/bindings/native.js 1:15-40
Module not found: Error: Can't resolve '../bin-package' in '/Users/zbloss/Projects/extinct-sounds/website/node_modules/tokenizers/bindings'

webpack compiled with 1 error and 82 warnings
No issues found.

```

System Information
| | |
|-|-|
| OS | MacOS 13.0 |
| Chip | M2 |
| Node | 13.14.0 |
| npm | 6.14.4 |

**Comment by Narsil** [comment]
Hmm we are building prebuilt wheels for Python and MacOS M1, however it's been much longer since I looked at Node... 

Could you try compiling from source and tell if it works ?
https://huggingface.co/docs/transformers/installation#install-from-source

**Comment by zbloss** [comment]
You're suggesting compiling the node package from source right? Double checking because the docs you linked show how to install from source in python.

**Comment by zbloss** [comment]
The following code runs fine

```bash

git clone https://github.com/huggingface/tokenizers
cd tokenizers/bindings/node
npm ci

```

Here is the error I get from running `npm run compile`

```bash
error: could not compile `node` due to previous error
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/zbloss/Projects/tokenizers/bindings/node/node_modules/neon-cli/lib/target.js:98:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zbloss/Projects/tokenizers/bindings/node/node_modules/neon-cli/lib/target.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tokenizers@0.13.2 compile: `neon build --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tokenizers@0.13.2 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zbloss/.npm/_logs/2022-11-04T00_31_16_380Z-debug.log


```


And here is the referenced log file

```log

zbloss@zachs-air tokenizers % cat /Users/zbloss/.npm/_logs/2022-11-04T00_31_16_380Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/zbloss/.nvm/versions/node/v13.14.0/bin/node',
1 verbose cli   '/Users/zbloss/.nvm/versions/node/v13.14.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compile'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle tokenizers@0.13.2~precompile: tokenizers@0.13.2
6 info lifecycle tokenizers@0.13.2~compile: tokenizers@0.13.2
7 verbose lifecycle tokenizers@0.13.2~compile: unsafe-perm in lifecycle true
8 verbose lifecycle tokenizers@0.13.2~compile: PATH: /Users/zbloss/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/zbloss/Projects/tokenizers/bindings/node/node_modules/.bin:/Users/zbloss/opt/miniconda3/condabin:/Users/zbloss/.pyenv/shims:/Users/zbloss/.nvm/versions/node/v13.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/zbloss/.cargo/bin
9 verbose lifecycle tokenizers@0.13.2~compile: CWD: /Users/zbloss/Projects/tokenizers/bindings/node
10 silly lifecycle tokenizers@0.13.2~compile: Args: [ '-c', 'neon build --release' ]
11 silly lifecycle tokenizers@0.13.2~compile: Returned: code: 1  signal: null
12 info lifecycle tokenizers@0.13.2~compile: Failed to exec compile script
13 verbose stack Error: tokenizers@0.13.2 compile: `neon build --release`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/zbloss/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/zbloss/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid tokenizers@0.13.2
15 verbose cwd /Users/zbloss/Projects/tokenizers/bindings/node
16 verbose Darwin 22.1.0
17 verbose argv "/Users/zbloss/.nvm/versions/node/v13.14.0/bin/node" "/Users/zbloss/.nvm/versions/node/v13.14.0/bin/npm" "run" "compile"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error tokenizers@0.13.2 compile: `neon build --release`
22 error Exit status 1
23 error Failed at the tokenizers@0.13.2 compile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]



```

**Comment by kevinlu1248** [comment]
I'm getting the same issue. I'm getting

```
ERROR in ./node_modules/tokenizers/bindings/native.js 1:15-40
Module not found: Error: Can't resolve '../bin-package' in '/home/kevin/aline-chrome-extension/node_modules/tokenizers/bindings'
resolve '../bin-package' in '/home/kevin/aline-chrome-extension/node_modules/tokenizers/bindings'
  using description file: /home/kevin/aline-chrome-extension/node_modules/tokenizers/package.json (relative path: ./bindings)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/kevin/aline-chrome-extension/node_modules/tokenizers/package.json (relative path: ./bin-package)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/kevin/aline-chrome-extension/node_modules/tokenizers/bin-package is not a file
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /home/kevin/aline-chrome-extension/node_modules/tokenizers/bin-package.tsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/kevin/aline-chrome-extension/node_modules/tokenizers/bin-package.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/kevin/aline-chrome-extension/node_modules/tokenizers/bin-package.js doesn't exist
      as directory
        existing directory /home/kevin/aline-chrome-extension/node_modules/tokenizers/bin-package
          using description file: /home/kevin/aline-chrome-extension/node_modules/tokenizers/package.json (relative path: ./bin-package)
            using path: /home/kevin/aline-chrome-extension/node_modules/tokenizers/bin-package/index
              using description file: /home/kevin/aline-chrome-extension/node_modules/tokenizers/package.json (relative path: ./bin-package/index)
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/kevin/aline-chrome-extension/node_modules/tokenizers/bin-package/index doesn't exist
                .tsx
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/kevin/aline-chrome-extension/node_modules/tokenizers/bin-package/index.tsx doesn't exist
                .ts
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/kevin/aline-chrome-extension/node_modules/tokenizers/bin-package/index.ts doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/kevin/aline-chrome-extension/node_modules/tokenizers/bin-package/index.js doesn't exist
 @ ./node_modules/tokenizers/bindings/utils.js 1:15-34
 @ ./node_modules/tokenizers/index.js 28:14-41
 @ ./src/background.ts 51:19-40

webpack 5.75.0 compiled with 1 error in 60 ms
```

Did some searching and it looks like it has something to do with 

```json
  "binary": {
    "module_name": "index",
    "module_path": "./bin-package",
    "host": "https://tokenizers-releases.s3.amazonaws.com/node",
    "package_name": "{module_name}-v{version}-{node_abi}-{platform}-{arch}-{libc}.tar.gz",
    "remote_path": "{version}"
  }
```

Not sure what module_path is referring to. Did I not download something I'm supposed to?

**Comment by Narsil** [comment]
Sorry I have no idea what's going on for you.

`npm install` should work.

Could you try building from source and see if it works ?

```
cd bindings/node
npm run compile
npm run test
```
