### ISSUE TITLE
`stride` assertion check no longer catches all invalid truncation parameters

### ISSUE THREAD

**Issue by boyleconnor** [huggingface/tokenizers#1326]
Why was [this line](https://github.com/huggingface/tokenizers/blob/9a93c50c25c1e0b73a85584f327113bcbef5ac80/tokenizers/src/tokenizer/mod.rs#L608) changed in 9a93c50? I am pretty sure it should be `<=`, not `<`. [Further downstream](https://github.com/huggingface/tokenizers/blob/9a93c50c25c1e0b73a85584f327113bcbef5ac80/tokenizers/src/tokenizer/encoding.rs#L319), when the truncation is actually run, it will panic if `!(stride < max_len)`, i.e. `max_len <= stride`, so I don't see why this check shouldn't match.

I tested with the following code (reminder: BERT adds exactly 2 special tokens in this case, so the effective max length is actually `8`):

```python
tokenizer = Tokenizer.from_pretrained('bert-base-cased')
tokenizer.enable_truncation(max_length=10, stride=8)  # This should fail but doesn't
```

which doesn't create an error (even though it should). But it will (correctly) produce an error when the following is run:

```python
tokenizer.encode("This piece of text is at least ten tokens long. In fact, it is likely many more than that.")
```

```
Traceback (most recent call last):
  File "/home/connor/PycharmProjects/tokenizers/test_stride_warning.py", line 11, in <module>
    main()
  File "/home/connor/PycharmProjects/tokenizers/test_stride_warning.py", line 7, in main
    tokenizer.encode("This piece of text is at least ten tokens long. In fact, it is likely many more than that.")
pyo3_runtime.PanicException: `stride` must be strictly less than `max_len=8` (note that `max_len` may be shorter than the max length of the original model, as it subtracts the number of special characters
```

**Comment by boyleconnor** [comment]
@Narsil it looks like you made (or at least merged in) this change, which I don't see any discussion of. Can I open a PR to reverse the change (unless there is a good reason why the two checks don't match)?
