### ISSUE TITLE
Tokenizer Training Errors: pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: TryFromIntError(())

### ISSUE THREAD

**Issue by Chimaco37** [huggingface/tokenizers#1698]
Hi, I was trying to train a Unigram tokenizer with DNA sequence data. And this is the code I use to train:

```
print("Unigram tokenizer")
tokenizer = Tokenizer(Unigram())
special_tokens = ["<cls>", "<sep>", "<unk>", "<pad>", "<mask>", "<s>", "</s>"]
trainer = UnigramTrainer(special_tokens=special_tokens, vocab_size=Unigram_vocab_size, unk_token="<unk>", show_progress=True)
tokenizer.train_from_iterator(iterator=all_seqs, trainer=trainer)
tokenizer.save(join(output_folder, "SentencePiece_"+ str(vocab_size) + ".json"))
```

At first, I encountered this error:
(base) [shfa523g@login1.barnard slurm_stderr]$ cat slurm-12831381.out
thread '<unnamed>' panicked at /home/runner/work/tokenizers/tokenizers/tokenizers/src/models/unigram/trainer.rs:228:53:
called `Result::unwrap()` on an `Err` value: Internal
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/shfa523g/Chi_Internship/tokenizers_scripts/generate_tokenizers_parallel.py", line 90, in <module>
    tokenizer.train_from_iterator(iterator=all_seqs, trainer=trainer)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Internal

Then I found a similar issue description and did as what it said, the issue is here:
https://github.com/huggingface/tokenizers/issues/821#issuecomment-958144662

After I tried what it says, it gives me a new issue:
(base) [shfa523g@login1.barnard slurm_stderr]$ cat slurm-12861633.out
thread '<unnamed>' panicked at /home/shfa523g/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esaxx-rs-0.1.10/src/esa.rs:70:50:
called `Result::unwrap()` on an `Err` value: TryFromIntError(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/shfa523g/Chi_Internship/tokenizers_scripts/generate_tokenizers_parallel.py", line 90, in <module>
    tokenizer.train_from_iterator(iterator=all_seqs, trainer=trainer)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: TryFromIntError(())

I asked ChatGPT, it says it might be the sequences it took are too long, then I reduce it to a very small number but the same error keeps happening.

Please take a look, thank you very much!

**Comment by Chimaco37** [comment]
Update:
The sequence number I reduced is the chunk size I put in, the total amount of length didn't change. 
The reason I mention this is because when I reduce the whole dataset from 24 chromosomes into 1 single chromosome, it works and generate correct output.
So the problem now is: How can I train the Unigram tokenizer on a large scale dataset (whole 24 chromosomes)? Please help me.

**Comment by Asiiii-p** [comment]
May I ask if you have solved this problem? I have also been running genetic data tokenizer recently, and I have also encountered this problem

**Comment by Chimaco37** [comment]
> May I ask if you have solved this problem? I have also been running genetic data tokenizer recently, and I have also encountered this problem

No.. It will work if you train the tokenizer with part (few chromosomes) of the genome instead of all. For the question, no one reply....

**Comment by ArthurZucker** [comment]
Yeah you should activate truncation, otherwise we are probably gonna merge #1713 should help
