### ISSUE TITLE
Error on tokenizing dataset with electra-base-discriminator tokenizer

### ISSUE THREAD

**Issue by mrm8488** [huggingface/tokenizers#307]
Hi, I got the following error/exception on using  the script to fine tune a model (electra-base discriminator in this case) on squad (v2 in this case) dataset:
```python
assert len(ids) > num_tokens_to_remove
```
Full error message:

```python
06/15/2020 23:12:09 - WARNING - transformers.tokenization_utils_base -   Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'only_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you may want to check this is the right behavior.
06/15/2020 23:12:09 - WARNING - transformers.tokenization_utils_base -   Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'only_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you may want to check this is the right behavior.
06/15/2020 23:12:09 - WARNING - transformers.tokenization_utils_base -   Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'only_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you may want to check this is the right behavior.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/transformers/data/processors/squad.py", line 142, in squad_convert_example_to_features
    return_token_type_ids=True,
  File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py", line 1503, in encode_plus
    **kwargs,
  File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils.py", line 372, in _encode_plus
    verbose=verbose,
  File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils.py", line 578, in _prepare_for_model
    stride=stride,
  File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils.py", line 675, in truncate_sequences
    assert len(ids) > num_tokens_to_remove
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/transformers/examples/question-answering/run_squad.py", line 828, in <module>
    main()
  File "/content/transformers/examples/question-answering/run_squad.py", line 766, in main
    train_dataset = load_and_cache_examples(args, tokenizer, evaluate=False, output_examples=False)
  File "/content/transformers/examples/question-answering/run_squad.py", line 460, in load_and_cache_examples
    threads=args.threads,
  File "/usr/local/lib/python3.6/dist-packages/transformers/data/processors/squad.py", line 331, in squad_convert_examples_to_features
    disable=not tqdm_enabled,
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 320, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AssertionError
convert squad examples to features:   0% 129/130319 [00:03<1:05:55, 32.91it/s]
```

Script used:
```bash
python /content/transformers/examples/question-answering/run_squad.py\
  --model_type electra \
  --model_name_or_path google/electra-base-discriminator \
  --tokenizer_name google/electra-base-discriminator \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file /content/dataset/train-v2.json \
  --predict_file /content/dataset/dev-v2.json \
  --per_gpu_train_batch_size 16 \
  --learning_rate 3e-5 \
  --num_train_epochs 5 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /content/model_output \
  --overwrite_output_dir \
  --save_steps 1000 \
  --version_2_with_negative 
```

Environment info:
```
- `transformers` version: 2.11.0
- Platform: Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.0+cu101 (True)
- Tensorflow version (GPU?): 2.2.0 (True)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
```

**Comment by epetros** [comment]
Facing the same issue with squad_v1_pt.

**Comment by yuhongqian** [comment]
**Possible Solution**
I got the same error while training on some other dataset. This error can happen when you have a short first input sequence and a long second input sequence. To resolve this issue, pass `truncation="only_second"` or `truncation="longest_first"` to `encode_plus` according to your needs. 

**Explanation with details:** 
As the warning suggests, you are using the default "only_first" truncation strategy (I think this is the default of your tokenizer `electra-base-discriminator`). This strategy truncates only the first input sequence so that (first sequence length + second sequence length + special token length) <= max_seq_length. 

In order to perform this truncation strategy correctly, `_prepare_for_model` calculates num_tokens_to_remove = total_len - max_length. After that, `truncate_sequences`, makes sure the first sequence has enough number of tokens to be truncated by `assert len(ids) > num_tokens_to_remove`, where `len(ids)` corresponds to the length of the first input sequence. Therefore, if the second sequence is long, num_tokens_to_remove can be greater than `len(ids)`, and the assertion will fail.

**Comment by sergeigofman** [comment]
I encounter this issue with SQuAD 1.1 too. In order to overcome it, I forced truncation_strategy to TruncationStrategy.ONLY_SECOND. However, I am not sure that it will have good results with this truncation. Can you please help resolve this to make SQuAD usable?

**Comment by n1t0** [comment]
I don't think this has any relation to the `tokenizers` library (this repository). Can you open an issue on https://github.com/huggingface/transformers instead?
