### ISSUE TITLE
There's a bug with building BPE

### ISSUE THREAD

**Issue by Narsil** [huggingface/tokenizers#439]
seems `u64` branch cannot fix the problem.
the error
```
thread '<unnamed>' panicked at 'Trainer should know how to build BPE: MergeTokenOutOfVocabulary("##h##e")', /home/xxx/tokenizers/tokenizers/src/models/bpe/trainer.rs:573:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "train_wp.py", line 55, in <module>
    main()
  File "train_wp.py", line 50, in main
    bpe.train(args.inputs, vocab_size=args.vocab_size, special_tokens=special_tokens,
  File "/home/xxx/tokenizers/bindings/python/py_src/tokenizers/implementations/bert_wordpiece.py", line 117, in train
    self._tokenizer.train(trainer, files)
pyo3_runtime.PanicException: Trainer should know how to build BPE: MergeTokenOutOfVocabulary("##h##e")
```

_Originally posted by @guolinke in https://github.com/huggingface/tokenizers/issues/437#issuecomment-699296355_

**Comment by Narsil** [comment]
The problem was linked to continuing subwordprefix that was not taken into account while getting the ids of merges.
