### ISSUE TITLE
Branch `python-mutable-components` and transformers v3.5.1 not working together

### ISSUE THREAD

**Issue by Tomiinek** [huggingface/tokenizers#545]
I am not sure whether is this the right place to write, but I encountered an issue while using `transformers==3.5.1` together with the branch `python-mutable-components` (#530). Master works without any problems, so I believe that the problem is caused by the current changes.

Minimal not working example:
```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('gpt2')
```
Stack trace:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File ".../lib/python3.8/site-packages/transformers/tokenization_auto.py", line 341, in from_pretrained
  return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
File ".../lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1652, in from_pretrained
  return cls._from_pretrained(
File ".../lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1750, in _from_pretrained
  special_tokens = tokenizer.all_special_tokens
File ".../lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1115, in all_special_tokens
  all_toks = [str(s) for s in self.all_special_tokens_extended]
File ".../lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1131, in all_special_tokens_extended
  all_toks = list(OrderedDict.fromkeys(all_toks))
TypeError: unhashable type: 'tokenizers.AddedToken'
```

**Comment by n1t0** [comment]
Thank you @Tomiinek!

It seems like adding `__richcmp__` without adding `__hash__` makes a type unhashable...

**Comment by n1t0** [comment]
Can you try again with the latest version of `python-mutable-components`?

**Comment by Tomiinek** [comment]
Perfect! Everything seems to be ok. Thank you very much.

**Comment by n1t0** [comment]
Awesome! Thank you for your help!
