### ISSUE TITLE
BertWordPieceTokenizer error

### ISSUE THREAD

**Issue by Sebduncan31** [huggingface/tokenizers#56]
Hi, the following code from the main example doesn't work:

tokenizer = BertWordPieceTokenizer("bert-base-uncased-vocab.txt", lowercase=True)

---

Errors: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.local/lib/python3.6/site-packages/tokenizers/implementations/bert_wordpiece.py", line 26, in __init__
    tokenizer = Tokenizer(WordPiece.from_files(vocab_file, unk_token=unk_token))
Exception: Error while initializing WordPiece

**Comment by Sebduncan31** [comment]
Downloading manually the file fixed the problem
