### ISSUE TITLE
Fast Roberta tokenizer does not accept pretokenized input

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/tokenizers#619]
I am running the following code with transformers==4.1.1. For `encode_plus` I see that the accepted type for `text` is `Union[TextInput, PreTokenizedInput, EncodedInput]` and `PreTokenizedInput = List[str]`. However, the code below still throws a TypeError. The issue does not arise when using the regular RobertaTokenizer class.

```python
from transformers import RobertaTokenizerFast

tokenizer = RobertaTokenizerFast.from_pretrained("roberta-base")

encoded = tokenizer.encode_plus(["Thanks",  "for", "the", "help"])
```

Throws a TypeError:

```
Traceback (most recent call last):
  File "C:/Users/bramv/AppData/Roaming/JetBrains/PyCharm2020.3/scratches/scratch_1.py", line 5, in <module>
    encoded = tokenizer.encode_plus(["Thanks",  "for", "the", "help"])
  File "C:\Users\bramv\.virtualenvs\jasper-tok2vec-4kc9ajCV\lib\site-packages\transformers\tokenization_utils_base.py", line 2444, in encode_plus
    return self._encode_plus(
  File "C:\Users\bramv\.virtualenvs\jasper-tok2vec-4kc9ajCV\lib\site-packages\transformers\models\gpt2\tokenization_gpt2_fast.py", line 169, in _encode_plus
    return super()._encode_plus(*args, **kwargs)
  File "C:\Users\bramv\.virtualenvs\jasper-tok2vec-4kc9ajCV\lib\site-packages\transformers\tokenization_utils_fast.py", line 448, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "C:\Users\bramv\.virtualenvs\jasper-tok2vec-4kc9ajCV\lib\site-packages\transformers\models\gpt2\tokenization_gpt2_fast.py", line 159, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "C:\Users\bramv\.virtualenvs\jasper-tok2vec-4kc9ajCV\lib\site-packages\transformers\tokenization_utils_fast.py", line 375, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
```

**Comment by n1t0** [comment]
Hi @BramVanroy ! You're missing a `is_split_into_words=True` for this to work. If this value is false, it expects strings.

**Comment by BramVanroy** [comment]
Ah, that makes sense. I guess the reason is to be able to distinguish between pretokenized text and a batch of strings? Got it.
