### ISSUE TITLE
None of the listed mBART-large-50 models work

### ISSUE THREAD

**Issue by IamAdiSri** [huggingface/tokenizers#633]
Trying to load the tokenizer for [facebook/mBART-large-50](https://huggingface.co/facebook/mbart-large-50) or associated finetuned checkpoints [facebook/mbart-large-50-many-to-many-mmt](https://huggingface.co/facebook/mbart-large-50-many-to-many-mmt) and [facebook/mbart-large-50-many-to-many-mmt](https://huggingface.co/facebook/mbart-large-50-one-to-many-mmt) results in the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aditya.srivastava/opt/Python-3.8.2/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1768, in from_pretrained
    return cls._from_pretrained(
  File "/home/aditya.srivastava/opt/Python-3.8.2/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1782, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
  File "/home/aditya.srivastava/opt/Python-3.8.2/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1841, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/aditya.srivastava/opt/Python-3.8.2/lib/python3.8/site-packages/transformers/models/mbart/tokenization_mbart.py", line 109, in __init__
    self.set_src_lang_special_tokens(kwargs.get("src_lang", "en_XX"))
  File "/home/aditya.srivastava/opt/Python-3.8.2/lib/python3.8/site-packages/transformers/models/mbart/tokenization_mbart.py", line 199, in set_src_lang_special_tokens
    self.cur_lang_code = self.lang_code_to_id[src_lang]
KeyError: None
```

On the pages for these models the code snippets in the model cards say that we should load them using `MBart50TokenizerFast` but no such module exists in the transformers library. When I Google the module, it doesn't even show up elsewhere. Is this a documentation error or am I doing something wrong?

**Comment by Narsil** [comment]
Hi @IamAdiSri , did you check master ? They exist on master:

https://github.com/huggingface/transformers/blob/master/src/transformers/models/mbart/tokenization_mbart50_fast.py

It's a brand new model, so yes it hasn't landed in a published version yet !

Cheers.

**Comment by IamAdiSri** [comment]
I updated my code base to use the classes from the master branch however, when I try to run the example on the model card, I still get this error;

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-88d049aaf9c0> in <module>
      5 tokenizer.src_lang = "hi_IN"
      6 encoded_hi = tokenizer(article_hi, return_tensors="pt")
----> 7 generated_tokens = model.generate(
      8     **encoded_hi,
      9     forced_bos_token_id=tokenizer.lang_code_to_id["fr_XX"]

~/opt/Python-3.8.2/lib/python3.8/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     24         def decorate_context(*args, **kwargs):
     25             with self.__class__():
---> 26                 return func(*args, **kwargs)
     27         return cast(F, decorate_context)
     28 

~/opt/Python-3.8.2/lib/python3.8/site-packages/transformers/generation_utils.py in generate(self, input_ids, max_length, min_length, do_sample, early_stopping, num_beams, temperature, top_k, top_p, repetition_penalty, bad_words_ids, bos_token_id, pad_token_id, eos_token_id, length_penalty, no_repeat_ngram_size, num_return_sequences, decoder_start_token_id, use_cache, num_beam_groups, diversity_penalty, prefix_allowed_tokens_fn, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, **model_kwargs)
    831         if self.config.is_encoder_decoder:
    832             # add encoder_outputs to model_kwargs
--> 833             model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(input_ids, model_kwargs)
    834 
    835             # set input_ids as decoder_input_ids

~/opt/Python-3.8.2/lib/python3.8/site-packages/transformers/generation_utils.py in _prepare_encoder_decoder_kwargs_for_generation(self, input_ids, model_kwargs)
    376             argument: value for argument, value in model_kwargs.items() if not argument.startswith("decoder_")
    377         }
--> 378         model_kwargs["encoder_outputs"]: ModelOutput = encoder(input_ids, return_dict=True, **encoder_kwargs)
    379         return model_kwargs
    380 

~/opt/Python-3.8.2/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

TypeError: forward() got an unexpected keyword argument 'forced_bos_token_id'
```

Looking at the code in the master repository, I can't see the generate function taking that argument either so I'm unsure how to proceed with this.

@patil-suraj I was wondering if you could help me since you've been updating the model and the code here.

**Comment by IamAdiSri** [comment]
@Narsil can this issue be reopened considering even modules from master branch aren't working?

**Comment by n1t0** [comment]
Can you open an issue on `transformers`?

**Comment by IamAdiSri** [comment]
@n1t0 yes, my bad.
