### ISSUE TITLE
AttributeError: 'ByteLevelBPETokenizer' object has no attribute 'pad_token_id'

### ISSUE THREAD

**Issue by athenawisdoms** [huggingface/tokenizers#669]
Hello, I am trying to tokenize some numerical strings using a `WordLevel` tokenizer, create a data collator and eventually use it in a PyTorch DataLoader to train a new model from scratch.

```py
from transformers import DataCollatorForLanguageModeling
from tokenizers import ByteLevelBPETokenizer
from tokenizers.pre_tokenizers import Whitespace
from torch.utils.data import DataLoader, TensorDataset

data = ['4814 4832 4761 4523 4999 4860 4699 5024 4788 [UNK]']

# Tokenizer
tokenizer = ByteLevelBPETokenizer()
tokenizer.pre_tokenizer = Whitespace()
tokenizer.train_from_iterator(data, vocab_size=1000, min_frequency=1, 
    special_tokens=[
        "<s>",
        "</s>",
        "<unk>",
        "<mask>",
    ])

# Data Collator
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer, mlm=False
)

train_dataset = TensorDataset(torch.tensor(tokenizer(data, ......)))

# DataLoader
train_dataloader = DataLoader(
    train_dataset, 
    collate_fn=data_collator
)
```

However, an error is happening 

> AttributeError: 'ByteLevelBPETokenizer' object has no attribute 'pad_token_id'

```py
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/anaconda3/envs/x/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/anaconda3/envs/x/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/opt/anaconda3/envs/x/lib/python3.8/site-packages/transformers/data/data_collator.py", line 351, in __call__
    if self.tokenizer.pad_token_id is not None:
AttributeError: 'ByteLevelBPETokenizer' object has no attribute 'pad_token_id'
```

Hope someone can explain why these errors are happening, and how we can solve them.

Thanks!

**Comment by david-waterworth** [comment]
you need to convert you tokenizer from the `tokenizers` version to the `transformers` version. The easiest way I'm aware of is to save as a json file i.e.

```
tokenizer.save("tokenizer.json")
```

then

```
from transformers import PreTrainedTokenizerFast
PreTrainedTokenizerFast.from_pretrained("tokenizer.json")
```
