### ISSUE TITLE
Index out of bound scrash at src/tokenizer/normalizer.rs:382:21

### ISSUE THREAD

**Issue by leezu** [huggingface/tokenizers#692]
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 7 but the index is 7', /__w/tokenizers/tokenizers/tokenizers/src/tokenizer/normalizer.rs:382:21
PanicException: index out of bounds: the len is 7 but the index is 7
```

Reproducer:

```
from transformers import AutoTokenizer  # tokenizers 0.10.1
tokenizer = AutoTokenizer.from_pretrained('facebook/mbart-large-cc25')
tokenizer._tokenizer.encode('¯\x8fব')
```

**Comment by n1t0** [comment]
What about with `tokenizers==0.10.2`?
