### ISSUE TITLE
PanicException: no entry found for key when saving a custom trained a word level tokenizer

### ISSUE THREAD

**Issue by BluedragonXVI** [huggingface/tokenizers#776]
Hello, I am trying to save a custom tokenizer trained on a corpus, but am unable to save the trained tokenizer. Saving and loading worked just fine when I trained a BPE tokenizer with byte-level pre-tokenization (and was able to load this trained tokenizer json into an AutoTokenizer for use in the latest run_clm.py train-from-scratch-script), but when switching this BPE pipeline for a word level pipeline, I get the panic exception. Searching online about this error didn't seem to give any recent relevant results. I am using the latest dev version of transformers. The interesting thing is training this word level tokenizer works just fine, and it tokenizes my inputs like I expect, but doing the actual saving causes the panic exception.

```

"Train whitespacesplit word level tokenizer"
from tokenizers import Tokenizer
from tokenizers.pre_tokenizers import WhitespaceSplit
from tokenizers.models import WordLevel
from tokenizers.trainers import WordLevelTrainer

v2_special_tokens = ['<START>', '<DSTART>', '<PSTART>', '<END>', '<UNK>']
v2_tokenizer = Tokenizer(WordLevel(unk_token='<UNK>'))
v2_tok_trainer = WordLevelTrainer(special_tokens=v2_special_tokens)
v2_tokenizer.pre_tokenizer = WhitespaceSplit()
v2_files = ['./train_noestart.txt', './valid_noestart.txt']
v2_tokenizer.train(v2_files, v2_tok_trainer)

v2_tokenizer.save('./v2.json') # CAUSES PANIC EXCEPTION ERROR

```

As mentioned above, this same pipeline with a BPE model (instead of WordLevel) and byte-level pretokenization (instead of WhitespaceSplit) saves but something about the WordLevel is making it unable to save into a json file which I obviously need for any further downstream training/fine-tuning

**Comment by Narsil** [comment]
Do you mind sharing the actual stacktrace ? Or providing the files so we can reproduce ?

**Comment by BluedragonXVI** [comment]
`
PanicException: no entry found for key
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-18-52edfb2e6b90> in <module>
      4 #my_autotokenizer.save_pretrained('./AUTOTOKENIZER/my_autokenizer')
      5 
----> 6 v2_tokenizer.save('./v2.json')

PanicException: no entry found for key

`

**Comment by BluedragonXVI** [comment]
Stack trace from trying to run the run_clm.py script, referencing the save function

```

thread '<unnamed>' panicked at 'no entry found for key', /__w/tokenizers/tokenizers/tokenizers/src/models/mod.rs:36:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/draco/Environments/mainEnv/lib/python3.8/site-packages/multiprocess/pool.py", line 537, in _handle_tasks
    put(task)
  File "/mnt/c/Users/draco/Environments/mainEnv/lib/python3.8/site-packages/multiprocess/connection.py", line 209, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/mnt/c/Users/draco/Environments/mainEnv/lib/python3.8/site-packages/multiprocess/reduction.py", line 54, in dumps
    cls(buf, protocol, *args, **kwds).dump(obj)
  File "/mnt/c/Users/draco/Environments/mainEnv/lib/python3.8/site-packages/dill/_dill.py", line 454, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.8/pickle.py", line 901, in save_tuple
    save(element)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/mnt/c/Users/draco/Environments/mainEnv/lib/python3.8/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/mnt/c/Users/draco/Environments/mainEnv/lib/python3.8/site-packages/dill/_dill.py", line 1444, in save_function
    pickler.save_reduce(_create_function, (obj.__code__,
  File "/usr/lib/python3.8/pickle.py", line 692, in save_reduce
    save(args)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.8/pickle.py", line 901, in save_tuple
    save(element)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.8/pickle.py", line 886, in save_tuple
    save(element)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/mnt/c/Users/draco/Environments/mainEnv/lib/python3.8/site-packages/dill/_dill.py", line 1178, in save_cell
    pickler.save_reduce(_create_cell, (f,), obj=obj)
  File "/usr/lib/python3.8/pickle.py", line 692, in save_reduce
    save(args)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.8/pickle.py", line 886, in save_tuple
    save(element)
  File "/usr/lib/python3.8/pickle.py", line 578, in save
    rv = reduce(self.proto)
pyo3_runtime.PanicException: no entry found for key

```

**Comment by Narsil** [comment]
Ok, it seems your vocabulary is tainted and has holes (ids not affected to any token). Is that the case, did you modify by any means your vocabulary ?

**Comment by BluedragonXVI** [comment]
> Ok, it seems your vocabulary is tainted and has holes (ids not affected to any token). Is that the case, did you modify by any means your vocabulary ?

Removing the special_tokens arg in the WordLevelTrainer fixed the issue. Interestingly, using the special_tokens arg made the tokenizer reserve "space" for them smallest token ID number = number of special tokens + 1 but they weren't associated to an actual ID. I added the special tokens after training by using the trained tokenizer's add_special_tokens method. I'm assuming I didn't have a similar issue with the byte-level BPE trained tokenizer because byte-level pre-tokenization ensures any input can be encoded? Anyway thanks for your help!
