### ISSUE TITLE
Not able to import in python 3.5.2

### ISSUE THREAD

**Issue by ashispapu** [huggingface/tokenizers#84]
Hi team,

I have tried to install tokenizers using both pip and source. However, getting below error when importing.

>>> from tokenizers import BPETokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "NLP/NLP_venv/lib/python3.5/site-packages/tokenizers-0.1.1-py3.5-linux-x86_64.egg/tokenizers/__init__.py", line 10, in <module>
    from .implementations import (
  File "NLP/NLP_venv/lib/python3.5/site-packages/tokenizers-0.1.1-py3.5-linux-x86_64.egg/tokenizers/implementations/__init__.py", line 1, in <module>
    from .base_tokenizer import BaseTokenizer
  File "NLP/NLP_venv/lib/python3.5/site-packages/tokenizers-0.1.1-py3.5-linux-x86_64.egg/tokenizers/implementations/base_tokenizer.py", line 6
    _tokenizer: Tokenizer
              ^
SyntaxError: invalid syntax

**Comment by abhishekkrthakur** [comment]
Are there any plans to support python 3.5?

**Comment by mfuntowicz** [comment]
Should be fixed by #0b782e4 if you want to have a try and let us know :)

**Comment by abhishekkrthakur** [comment]
@mfuntowicz yes, thats what I tried in my fork. apparently, i was not able to build python bindings due to some un-related rust issues. Thank you for the fix. Will the python bindings be released soon?

**Comment by mfuntowicz** [comment]
I'll follow up internally and let you know when we can release

**Comment by mfuntowicz** [comment]
@ashispapu We just released the 0.2.1 which includes the aforementioned fix :). 

I'm closing for now, thanks for reporting the issue, feel free to reopen if needed.

**Comment by ashispapu** [comment]
Thanks for the update. it's fixed now.
