### ISSUE TITLE
TypeError: failed downcast to function

### ISSUE THREAD

**Issue by david-wb** [huggingface/tokenizers#885]
I'm getting an error when running the following code in Node.js using the tokenizers 0.8.2 npm package.

```typescript
    const tokenizer = await ByteLevelBPETokenizer.fromOptions({
      mergesFile: `${__dirname}/../src/tokenizers/gpt2-merges.txt`,
      vocabFile: `${__dirname}/../src/tokenizers/gpt2-vocab.json`,
    });
    const encoded = await tokenizer.encode("test"); // TypeError: failed downcast to function
    const decoded = await tokenizer.decode(encoded.ids);
    assert.equal(decoded, "test");
```

The error is 
```bash
TypeError: failed downcast to function
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at bound encode (internal/util.js:296:12)
    at ByteLevelBPETokenizer.encode (node_modules/tokenizers/implementations/tokenizers/base.tokenizer.js:68:35)
    at [...]
    at Generator.next (<anonymous>)
    at fulfilled (test/test-tokenizers.ts:5:58)
```

Any ideas why this might be happening?

**Comment by Narsil** [comment]
Can you share the full example ?

If you are awaiting without using `promisify` you're likely going to encounter issues:

```node
let { promisify } = require("util");
let { Tokenizer } = require("tokenizers/bindings/tokenizer");

const tokenizer = Tokenizer.fromPretrained("gpt2");

let encode = promisify(tokenizer.encode.bind(tokenizer));

(async () => {
    var output = await encode("Hello, y'all! How are you 😁 ?");
    console.log(output.getIds());
})();
```

This was taken from the docs: https://huggingface.co/docs/tokenizers/node/latest/quicktour.html

Does it help ?

**Comment by david-wb** [comment]
@Narsil That works thank you.
