### ISSUE TITLE
Type error using tokenizer.decode()

### ISSUE THREAD

**Issue by korakoe** [huggingface/tokenizers#999]
Using a custom BPE tokenizer and Custom tokens I get this type error:

```
Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\model\Model.py", line 154, in <module>
    result = tokenizer.decode(outputs, skip_special_tokens=True)
  File "C:\Users\user\Documents\GitHub\model\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 3304, in decode
    return self._decode(
  File "C:\Users\user\Documents\GitHub\model\venv\lib\site-packages\transformers\tokenization_utils.py", line 928, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "C:\Users\user\Documents\GitHub\model\venv\lib\site-packages\transformers\tokenization_utils.py", line 903, in convert_ids_to_tokens
    index = int(index)
TypeError: int() argument must be a string, a bytes-like object or a number, not "List"

Process finished with exit code 1
```

This is the code im using

```
tokenizer = GPT2Tokenizer.from_pretrained("Token")

    tokenizer.add_special_tokens({
        "additional_special_tokens":
        ["<start>",
        "<pad>",
        "<end>",
        "<unk>",
        "<Sentiment>",
        "</Sentiment>"]
    })

    model = GPT2LMHeadModel.from_pretrained("GPT-Model/checkpoint-6000").to("cuda", dtype=torch.float16)
    text = """Text"""
    
    encoded_input = tokenizer(text, return_tensors="pt", add_special_tokens=True).input_ids.to("cuda")
    
    outputs = model.generate(encoded_input, do_sample=True, max_length=1024, num_beams=5,
                             no_repeat_ngram_size=2, early_stopping=True, top_k=50, top_p=0.95,
                             pad_token_id=1, bos_token_id=0, eos_token_id=2)
    result = tokenizer.decode(outputs)

    print(result)
```

**Comment by korakoe** [comment]
Didnt need to include the tensor argument
